"""Regenerate the vendored pip constraints file for a Fabric Spark runtime.

Microsoft publishes each runtime's exact base Python environment as a conda
YML in github.com/microsoft/synapse-spark-runtime. This script turns that
manifest into a pip constraints file (``name==version`` per package) under
``tools/runtime_constraints/``. The publish scripts pass it to
``pip download -c`` so a bundle is resolved *against what the runtime already
ships*: any requirement that would force a runtime package to a different
version fails the publish, loudly, at build time — unless it is explicitly
allow-listed with a reason in that script's ``CONSTRAINT_OVERRIDES``. Wheels
that resolve to the runtime's own version are then pruned from the bundle.

That is the failure mode we want. ``pip check`` only ever sees *declared*
conflicts (in the incident this tooling comes from it named opentelemetry and
missed the protobuf upgrade that killed the Spark kernel); comparing against
the manifest catches what actually gets replaced.

Run by a human whenever a runtime update lands (the header records the
manifest hash, so re-running is a no-op until Microsoft changes the file)::

    python tools/refresh_runtime_constraints.py --runtime 2.0

Conda-to-PyPI mapping is deliberately simple: names are normalized (PEP 503),
a few known renames are mapped, versions that are not valid PEP 440 (system
libraries with conda-style versions) and OS-level packages are skipped. Pip
ignores constraints for names not in a resolve, so over-inclusion is harmless;
a *missing* mapping merely means that package is not gated (and, if it lands
in a bundle, shows up in the publish report as a replacement).
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

from onelake_bundle import CONSTRAINTS_DIR, RUNTIME_PROFILES, normalize_name, use_os_trust_store

# Conda package names whose PyPI project is spelled differently.
CONDA_TO_PYPI = {
    "msgpack-python": "msgpack",
    "matplotlib-base": "matplotlib",
    "pytables": "tables",
    "python-graphviz": "graphviz",
    "importlib_metadata": "importlib-metadata",
    "typing_extensions": "typing-extensions",
    "prompt_toolkit": "prompt-toolkit",
}

# Conda entries that are not Python distributions (or collide with a PyPI
# project of the same name but different meaning/versioning — tzdata is the
# IANA database in conda, a Python package on PyPI).
SKIP_NAMES = {
    "python", "pip", "setuptools", "wheel", "ca-certificates", "certifi-system",
    "openssl", "sqlite", "zlib", "ncurses", "readline", "bzip2", "xz", "tk", "tzdata",
    "expat", "libffi", "ld_impl_linux-64", "icu", "krb5", "libuuid", "libnsl",
    "libxcrypt", "python_abi", "nodejs", "openjdk", "r-base", "_libgcc_mutex",
    "_openmp_mutex", "brotli-bin", "gmp", "mpfr", "mpc", "pcre2", "yaml",
}

# PEP 440-ish sanity check; conda versions like "2025c" or "1.1.1w" fail it.
PEP440 = re.compile(
    r"^v?\d+(\.\d+)*((a|b|rc)\d+)?(\.post\d+)?(\.dev\d+)?(\+[0-9A-Za-z.]+)?$"
)

CONDA_LINE = re.compile(r"^\s*-\s*([A-Za-z0-9_.\-]+)=([^=\s]+)(=\S+)?\s*$")
PIP_LINE = re.compile(r"^\s*-\s*([A-Za-z0-9_.\-]+)==(\S+)\s*$")


def parse_manifest(text: str) -> dict[str, str]:
    """Return {normalized pypi name: version} from a Fabric runtime conda YML."""
    pins: dict[str, str] = {}
    for line in text.splitlines():
        match = PIP_LINE.match(line) or CONDA_LINE.match(line)
        if not match:
            continue
        raw_name, version = match.group(1), match.group(2)
        if raw_name.startswith(("lib", "_")) or raw_name in SKIP_NAMES:
            continue
        name = normalize_name(CONDA_TO_PYPI.get(raw_name, raw_name))
        if name in SKIP_NAMES or not PEP440.match(version):
            continue
        pins[name] = version
    return pins


def render(profile_version: str, source_url: str, digest: str, pins: dict[str, str]) -> str:
    header = [
        f"# Fabric Runtime {profile_version} base Python packages, as pip constraints.",
        "# GENERATED by tools/refresh_runtime_constraints.py — do not edit by hand.",
        f"# source: {source_url}",
        f"# manifest_sha256: {digest}",
        "# Consumed by tools/onelake_bundle.py (pip download -c) so a bundle can",
        "# never replace a runtime package without an explicit CONSTRAINT_OVERRIDES",
        "# entry in the publish script.",
        "",
    ]
    body = [f"{name}=={version}" for name, version in sorted(pins.items())]
    return "\n".join(header + body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", required=True, choices=sorted(RUNTIME_PROFILES))
    parser.add_argument(
        "--manifest-file",
        help="Read the manifest from a local file instead of fetching it (tests, offline).",
    )
    args = parser.parse_args()
    profile = RUNTIME_PROFILES[args.runtime]

    use_os_trust_store()  # corporate proxy CA lives in the OS store, not certifi
    if args.manifest_file:
        text = Path(args.manifest_file).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(profile.manifest_url, timeout=60) as response:  # noqa: S310 — fixed https URL
            text = response.read().decode("utf-8")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    pins = parse_manifest(text)
    if len(pins) < 50:
        raise SystemExit(f"Only {len(pins)} packages parsed from the manifest — format changed?")

    target = CONSTRAINTS_DIR / profile.constraints_file
    content = render(profile.version, profile.manifest_url, digest, pins)
    if target.is_file() and target.read_text(encoding="utf-8") == content:
        print(f"{target.relative_to(CONSTRAINTS_DIR.parent.parent)}: unchanged ({len(pins)} packages)")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"{target.relative_to(CONSTRAINTS_DIR.parent.parent)}: written ({len(pins)} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
